spring.application.name=FoodWasteCombat
spring.datasource.url=jdbc:postgresql://meticulous-empathy-x3sa.railway.internal:5432/$railway
spring.datasource.username=postgres
spring.datasource.password=NabRUvmZPTpbNJUrzevjwzVNeZwCIfXf
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
