spring.application.name=FoodWasteCombat
spring.datasource.url=jdbc:postgresql://postgres:dLurCbKooQDlKpIHOwIeUXweXHalogBZ@autorack.proxy.rlwy.net:17918/railway
spring.datasource.username=postgres
spring.datasource.password=dLurCbKooQDlKpIHOwIeUXweXHalogBZ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
