spring.application.name=FoodWasteCombat
spring.datasource.url=jdbc:postgres://${DATABASE_HOST:roundhouse.proxy.rlwy.net}:${DATABASE_PORT:46219}/${DATABASE_NAME:railway}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:HPUxJmNmFjoexQBfWAPnTYxVgWWeeXdM}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
